# Setup
title: Keto
tagline: Blog
description: Keto D. Zhang blogs
url: https://ketozhang.github.io
baseurl: /blog
permalink: pretty
paginate: 3

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - Makefile
  - Dockerfile
  - docker-compose.yml

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Keto D. Zhang
  url: https://twitter.com/ketozhang
